In [1]:
import src.extraction as extract
import src.transformations as transform
from statistics import mode
import pandas as pd

In [2]:
df_salaries = extract.acquire_salaries("https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_income")
df_salaries = transform.wiki_basic_clean(df_salaries)
df_salaries

,"States and Washington, D.C.",2018,2017,2016,2015,2014,2013,"Average annual growth rate (current dollars) in 2010-2019,Â %"
0,United States,"63,179","60,336","57,617","55,775","53,657","52,250",3.07%
1,"Washington, D.C.","85,203","82,372","75,506","75,628","71,648","67,572",4.72%
2,Maryland,"83,242","80,776","78,945","75,847","73,971","72,483",2.6%
3,Massachusetts,"79,835","77,385","75,297","70,628","69,160","66,768",3.67%
4,New Jersey,"81,740","80,088","76,126","72,222","71,919","70,165",2.66%
5,Hawaii,"80,212","77,765","74,511","73,486","69,592","68,020",3.12%
6,California,"75,277","71,805","67,739","64,500","61,933","60,190",3.76%
7,Connecticut,"76,348","74,168","73,433","71,346","70,048","67,098",2.34%
8,Washington,"74,073","70,979","67,106","64,129","61,366","58,405",3.93%
9,New Hampshire,"74,991","73,381","70,936","70,303","66,532","64,230",2.75%
10,Colorado,"71,953","69,117","65,685","63,909","61,303","58,823",4.03%
11,Virginia,"72,577","71,535","68,114","66,262","64,902","62,666",2.6%
12,Utah,"71,414","65,358","65,977","62,912","60,922","59,770",3.68%
13,Alaska,"74,346","73,181","76,440","73,355","71,583","72,237",1.75%
14,Minnesota,"70,315","68,388","65,599","63,488","61,481","60,702",3.35%
15,New York,"67,844","64,894","62,909","60,850","58,878","57,369",3.23%
16,Rhode Island,"64,340","63,870","60,596","58,073","54,891","55,902",3.49%
17,Delaware,"64,805","62,852","61,757","61,255","59,716","57,846",2.57%
18,Illinois,"65,030","62,992","60,960","59,588","57,444","56,210",3.01%
19,Oregon,"63,426","60,212","57,532","54,148","51,075","50,251",4.14%
20,Wyoming,"61,584","60,434","59,882","60,214","57,055","58,752",2.18%
21,North Dakota,"63,837","61,843","60,656","60,557","59,029","55,759",3.19%
22,Wisconsin,"60,773","59,305","56,811","55,638","52,622","51,467",3.04%
23,Texas,"60,629","59,206","56,565","55,653","53,035","51,704",3.11%
24,Pennsylvania,"60,905","59,105","56,907","55,702","53,234","52,007",2.85%
25,Nevada,"58,646","58,003","55,180","52,431","51,450","51,230",2.43%
26,Nebraska,"59,566","59,970","56,927","54,996","52,686","51,440",3.01%
27,Vermont,"60,782","57,513","57,677","56,990","54,166","52,578",2.74%
28,Kansas,"58,218","56,422","54,935","53,906","52,504","50,972",2.84%
29,Arizona,"59,246","56,581","53,558","51,492","50,068","48,510",3.19%
30,Georgia,"58,756","56,183","53,559","51,244","49,321","47,829",3.26%
31,Iowa,"59,955","58,570","56,247","54,736","53,712","52,229",2.84%
32,Idaho,"55,583","52,225","51,807","48,275","47,861","46,783",3.83%
33,Michigan,"56,697","54,909","52,491","51,084","49,847","48,273",3.06%
34,South Dakota,"56,274","56,521","54,467","53,017","50,979","48,947",2.93%
35,Florida,"55,462","52,594","50,860","49,426","47,463","46,036",3.25%
36,Maine,"55,602","55,277","53,079","51,494","49,462","46,974",2.84%
37,Ohio,"56,111","54,021","52,344","51,075","49,308","48,081",2.96%
38,Indiana,"55,746","54,181","52,314","50,532","49,446","47,529",2.88%
39,Missouri,"54,478","53,578","51,746","50,238","48,363","46,931",2.92%
40,North Carolina,"53,855","52,752","50,584","47,830","46,556","45,906",3.16%
41,Montana,"55,328","53,386","50,027","49,509","46,328","46,972",3.3%
42,South Carolina,"52,306","50,570","49,501","47,238","45,238","44,163",3.29%
43,Tennessee,"52,375","51,340","48,547","47,275","44,361","44,297",3.41%
44,Oklahoma,"51,924","50,051","49,176","48,568","47,529","45,690",2.91%
45,Kentucky,"50,247","48,375","46,659","45,215","42,958","43,399",3.01%
46,New Mexico,"47,169","46,744","46,748","45,382","44,803","43,872",2.37%
47,Alabama,"49,861","48,123","46,257","44,765","42,830","42,849",2.76%
48,Louisiana,"47,905","46,145","45,146","45,727","44,555","44,164",2.06%
49,Arkansas,"47,062","45,869","44,334","41,995","41,262","40,511",2.76%
50,West Virginia,"44,097","43,469","43,385","42,019","41,059","41,253",2.76%
51,Mississippi,"44,717","43,529","41,754","40,593","39,680","37,963",2.44%

In [3]:
df_salaries.to_csv("data/us_state_avarege_annual_salary_2018-2013.csv")

In [4]:
df = extract.acquire_data("US_gun_violence")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239677 entries, 0 to 239676
Data columns (total 29 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   incident_id                  239677 non-null  int64
 1   date                         239677 non-null  object
 2   state                        239677 non-null  object
 3   city_or_county               239677 non-null  object
 4   address                      223180 non-null  object
 5   n_killed                     239677 non-null  int64
 6   n_injured                    239677 non-null  int64
 7   incident_url                 239677 non-null  object
 8   source_url                   239209 non-null  object
 9   incident_url_fields_missing  239677 non-null  bool
 10  congressional_district       227733 non-null  float64
 11  gun_stolen                   140179 non-null  object
 12  gun_type                     140226 non-null  object
 13  incident_characteristics     239351 non-null  object
 14  latitude                     231754 non-null  float64
 15  location_description         42089 non-null   object
 16  longitude                    231754 non-null  float64
 17  n_guns_involved              140226 non-null  float64
 18  notes                        158660 non-null  object
 19  participant_age              147379 non-null  object
 20  participant_age_group        197558 non-null  object
 21  participant_gender           203315 non-null  object
 22  participant_name             117424 non-null  object
 23  participant_relationship     15774 non-null   object
 24  participant_status           212051 non-null  object
 25  participant_type             214814 non-null  object
 26  sources                      239068 non-null  object
 27  state_house_district         200905 non-null  float64
 28  state_senate_district        207342 non-null  float64
dtypes: bool(1), float64(6), int64(3), object(19)
memory usage: 51.4+ MB

In [5]:
df_clean = transform.kaggle_basic_clean(df)
df_trans = transform.basic_transf(df_clean)

In [7]:
df_final = transform.final_clean(df_trans)
df_final.to_csv("data/clean_weapons.csv")

In [8]:
df_final

,date,state,city_or_county,n_killed,n_injured,gun_stolen,gun_type,incident_characteristics,latitude,longitude,n_guns_involved,state_house_district,state_senate_district,n_victims,n_suspects,n_women_involved,n_men_involved,age_group
0,2013-01-01,Pennsylvania,Mckeesport,0,4,Unknown,Unknown,Mass shooting,40.3467,-79.8559,NaN,NaN,NaN,4,1,1,3,Adult 18+
1,2013-01-01,California,Hawthorne,1,3,Unknown,Unknown,Mass shooting,33.9090,-118.3330,NaN,62.0,35.0,4,1,0,1,Adult 18+
2,2013-01-01,Ohio,Lorain,1,3,Unknown,Unknown,Shot - Wounded/Injured,41.4455,-82.1377,2.0,56.0,13.0,3,2,0,5,Adult 18+
3,2013-01-05,Colorado,Aurora,4,0,Unknown,Unknown,Drug involvement,39.6518,-104.8020,NaN,40.0,28.0,3,1,1,3,Adult 18+
4,2013-01-07,North Carolina,Greensboro,2,2,Unknown,Handgun,Domestic Violence,36.1140,-79.9569,2.0,62.0,27.0,3,1,2,2,Adult 18+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239671,2018-03-31,Washington,Spokane (Spokane Valley),0,0,Unknown,Unknown,Non-Shooting Incident,47.6638,-117.2350,1.0,4.0,4.0,0,1,0,1,Adult 18+
239673,2018-03-31,Louisiana,Natchitoches,1,0,Unknown,Unknown,Suicide,31.7537,-93.0836,1.0,23.0,31.0,1,1,0,2,Adult 18+
239674,2018-03-31,Louisiana,Gretna,0,1,Unknown,Unknown,Shot - Wounded/Injured,29.9239,-90.0442,1.0,85.0,7.0,1,0,0,1,Adult 18+
239675,2018-03-31,Texas,Houston,1,0,Unknown,Unknown,Suicide,29.7201,-95.6110,1.0,149.0,17.0,1,0,0,1,Adult 18+
239676,2018-03-31,Maine,Norridgewock,2,0,Unknown,Shotgun,Domestic Violence,44.7293,-69.7691,2.0,111.0,3.0,1,1,1,1,Adult 18+